#ifndef NYAST_BASE_CLASS_LIBRARY_CLASS_DESCRIPTION_HPP
#define NYAST_BASE_CLASS_LIBRARY_CLASS_DESCRIPTION_HPP

#pragma once

#include "Behavior.hpp"

#endif //NYAST_BASE_CLASS_LIBRARY_CLASS_DESCRIPTION_HPP
